### ISSUE TITLE
How to use more than one filter in the sametime?

### ISSUE THREAD

**Issue by fantao005x** [CyberAgent/android-gpuimage#122]
As I know we can use 'mGPUImage.setFilter(mFilter);'  to set a new filter instead the old one.
But how can i use more than one filter in the same time when i in Camera preview state?

**Comment by eosrei** [comment]
Link to the related source: https://github.com/CyberAgent/android-gpuimage/blob/bf0bfdef9fe78980ee836402edc8211fd679826c/library/src/jp/co/cyberagent/android/gpuimage/GPUImageFilterGroup.java Please close if this is correct.
