### ISSUE TITLE
Filter with ACV sometimes returns black picture

### ISSUE THREAD

**Issue by johnlomboy** [CyberAgent/android-gpuimage#150]
Hello all,

I am trying to filter an image after camera capture using acv file but sometimes it returns black after saving it to device storage using gpuimage.savetopictures method. Can help me figure this out? I would also like to know conceptually on how the image goes black. I was assuming it is due to super high image quality that the device could not handle or some super memory consumption.

P.S.: I saw this post (like https://github.com/CyberAgent/android-gpuimage/issues/49) and I am curious about their methods but could not somehow figure out on how they manage it.

**Comment by akonior** [comment]
Please put your code into **synchronized** block or method. `saveToPictures` may not be thread safe.

**Comment by johnlomboy** [comment]
Ok, will try and test it, thanks.
