### ISSUE TITLE
Remove custom GPUFilter in GPUImageFilterGroup

### ISSUE THREAD

**Issue by dockusan** [CyberAgent/android-gpuimage#162]
I have a bitmap with many filter: Blurfilter and sepiafilter and many other filter
```
GPUImageFilterGroup mFilterGroup = new GPUImageFilterGroup();
mFilterGroup.addFilter(new GPUImageSepiaFilter(1));
mFilterGroup.addFilter(new GPUImageGaussianBlurFilter(1));
//some other filter 
//....
GPUImage gpuImg = new GPUImage(this);
gpuImg.setFilter(mFilterGroup);
gpuImg.setBitmap(bitmap);

```
How to remove custom filter as blur and keep sepia and other?
It's mean, Image not contain blur effect.

**Comment by AnthonyUccello** [comment]
That strikes me as difficult to do (you'd need to reverse the bitmap manipulations). I think you'd be better off keeping track of the filters you apply, and if one is removed, start the whole chain again from the start (with the original picture) and just skip the filter you wanted removed.

**Comment by dockusan** [comment]
Thank @AnthonyUccello. I did it this issue.

**Comment by ZUCheema** [comment]
I had same problem in removing all applied filters in a group, I added GPUImageBrightnessFilter which helped to restore image to original, i.e No filter.
