### ISSUE TITLE
How to apply two filter image to a source bitmap

### ISSUE THREAD

**Issue by SwordBearer** [CyberAgent/android-gpuimage#177]
I have a source bitmap,and a LUT file , a mask file, what i want is combine the LUT effect and mask effect with source bitmap, here is my code:
 
/* first apply the LUT effect */
GPUImageLookupFilter lutFilter = new GPUImageLookupFilter();
lutFilter.setBitmap(lutBmp);
GPUImage image = new GPUImage(context);
image.setImage(sourceBmp);
image.setFilter(lutFilter);
Bitmap destBmp = image.getBitmapWithFilterApplied();

/*then, apply the mask effect */
if (maskBmp != null) {
            GPUImageMultiplyBlendFilter blendFilter = new GPUImageMultiplyBlendFilter();
            blendFilter.setBitmap(maskBmp);
            GPUImage image2 = new GPUImage(context);
            image2.setFilter(blendFilter);
            image2.setImage(destBmp);
            destBmp = image2.getBitmapWithFilterApplied();
 }

finally ,the destBmp is definitely what i want, but the only thing i worry about is the time, every this two step need about 65ms, so i have to wait 130ms until get the final bitmap.

Is there any way to combine two step to one? 
sorry for my English :)

**Comment by SwordBearer** [comment]
ignore me ,I found the GPUImageFilterGroup class , great~

**Comment by qujc** [comment]
you helped me~
