### ISSUE TITLE
Front Facing Camera Not Full screen

### ISSUE THREAD

**Issue by deshan** [CyberAgent/android-gpuimage#317]
jp.co.cyberagent.android.gpuimage.sample.activity.ActivityCamera

Pls see the screen shot, the front camera is not full screen in some phones? 
Front cam renders in 1/4 of the screen and last frame of the back camera  still in the view.

![screenshot_2016-09-21-15-00-23](https://cloud.githubusercontent.com/assets/234754/18705556/569b5454-800c-11e6-8870-74b86f8735f1.png)

**Comment by ngThu** [comment]
releaseCamera();
gpuImage.deleteImage();
mCurrentCameraId = (mCurrentCameraId + 1) % mCameraHelper.getNumberOfCameras();
setUpCamera(mCurrentCameraId);

You need to add line: "gpuImage.deleteImage();"

Hope I can help you!

**Comment by deshan** [comment]
Thanks ngThu

That worked for me.

Thanks again!

2016-09-24 10:34 GMT+05:30 ngThu <notifications@github.com>:

**Comment by ngThu** [comment]
No problem ^^

**Comment by coderlin** [comment]
Thx!
