### ISSUE TITLE
useDeprecatedNdk problem

### ISSUE THREAD

**Issue by oguzgu** [CyberAgent/android-gpuimage#378]
Hi,

I get build error as:

Error:Execution failed for task ':library:compileDebugNdk'.
> Error: Flag android.useDeprecatedNdk is no longer supported and will be removed in the next version of Android Studio.  Please switch to a supported build system.
  Consider using CMake or ndk-build integration. For more information, go to:
   https://d.android.com/r/studio-ui/add-native-code.html#ndkCompile
   To get started, you can use the sample ndk-build script the Android
   plugin generated for you at:
   android-gpuimage-master/library/build/intermediates/ndk/debug/Android.mk
  Alternatively, you can use the experimental plugin:
   https://developer.android.com/r/tools/experimental-plugin.html
  To continue using the deprecated NDK compile for another 60 days, set 
  android.deprecatedNdkCompileLease=1511898978137 in gradle.properties

**Comment by oguzgu** [comment]
Remove useDeprecatedNdk from gradle properties

Right click project and click "Link C++ Project with Gradle" then select path android-gpuimage-master/library/build/intermediates/ndk/debug/Android.mk 

this worked for me

**Comment by agi-umar** [comment]
ABIs [armeabi-v7a, arm64-v8a, x86, x86_64] are not supported for platform. Supported ABIs are [armeabi-v7a, arm64-v8a, x86, x86_64].

**Comment by haribhai** [comment]
#oguzgu Thank You so much man. adding android.mk (C:\Users\MyUser\Downloads\android-ndk-r19c\sources\android\native_app_glue\Android.mk) worked perfectly.

**Comment by priyankith** [comment]
> #oguzgu Thank You so much man. adding android.mk (C:\Users\MyUser\Downloads\android-ndk-r19c\sources\android\native_app_glue\Android.mk) worked perfectly.

Hey, i tried a combination of oguzgu and haribhai's answer, where i found an Android.mk in my ndk, but I've encountered a very weird issue. It all goes well till i click 'OK'
![Untitled](https://user-images.githubusercontent.com/39912804/63766589-1d898e00-c8e9-11e9-96e7-a4e6c583eed9.png)

which doesnt seem to work. Nothing happens. Where am I going wrong ? Please help.
